name: Issues Event Handler

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  log-issue-details:
    name: Log Issue Details
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Output Issue Event Details
      run: |
        echo "=== Issue Event Details ==="
        echo "Event Type: ${{ github.event_name }}"
        echo "Action: ${{ github.event.action }}"
        echo "Issue Number: ${{ github.event.issue.number }}"
        echo "Issue Title: ${{ github.event.issue.title }}"
        echo "Issue State: ${{ github.event.issue.state }}"
        echo "Issue URL: ${{ github.event.issue.html_url }}"
        echo "Created At: ${{ github.event.issue.created_at }}"
        echo "Updated At: ${{ github.event.issue.updated_at }}"
        echo "User: ${{ github.event.issue.user.login }}"
        echo "User Type: ${{ github.event.issue.user.type }}"
        
        echo ""
        echo "=== GitHub Context Details ==="
        echo "Repository: ${{ github.repository }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "Actor: ${{ github.actor }}"
        echo "SHA: ${{ github.sha }}"
        echo "Ref: ${{ github.ref }}"
        echo "Ref Name: ${{ github.ref_name }}"
        echo "Ref Type: ${{ github.ref_type }}"
        echo "Head Ref: ${{ github.head_ref }}"
        echo "Base Ref: ${{ github.base_ref }}"
        
        echo ""
        echo "=== Issue Labels ==="
        if [ "${{ github.event.issue.labels }}" != "[]" ]; then
          echo "${{ github.event.issue.labels }}" | jq -r '.[].name' | while read label; do
            echo "- $label"
          done
        else
          echo "No labels"
        fi
        
        echo ""
        echo "=== Issue Assignees ==="
        if [ "${{ github.event.issue.assignees }}" != "[]" ]; then
          echo "${{ github.event.issue.assignees }}" | jq -r '.[].login' | while read assignee; do
            echo "- $assignee"
          done
        else
          echo "No assignees"
        fi
        
        echo ""
        echo "=== Issue Milestone ==="
        if [ "${{ github.event.issue.milestone }}" != "null" ]; then
          echo "Milestone: ${{ github.event.issue.milestone.title }}"
          echo "Milestone Description: ${{ github.event.issue.milestone.description }}"
          echo "Milestone State: ${{ github.event.issue.milestone.state }}"
        else
          echo "No milestone"
        fi
        
        echo ""
        echo "=== Issue Body Preview ==="
        echo "${{ github.event.issue.body }}" | head -10
        if [ "$(echo "${{ github.event.issue.body }}" | wc -l)" -gt 10 ]; then
          echo "... (truncated)"
        fi 